### ISSUE TITLE
AAI calculation error

### ISSUE THREAD

**Issue by JA00156** [lebsnu/ezaai#11]
Hello. I am totally appreciative with all the efforts poured in creating this AAI tool. Well done.

I have just some issue with the second step, the calculation of AAI. I have successfully extracted the DB from my genome data files. However, whenever I run the command for the AAI calculation, I got this error prompt:
MAR 07 16:12:03] EzAAI   |:  EzAAI - v1.2 [Mar. 2022]
[MAR 07 16:12:42] EzAAI   |:  Calculating AAI... [Task 1/5776]
java.io.FileNotFoundException: /tmp/31f9c2de403cfb4b_faa/i0.faa (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at leb.process.ProcCalcPairwiseAAI.pairwiseMmseqs(ProcCalcPairwiseAAI.java:308)
	at leb.process.ProcCalcPairwiseAAI.calculateProteomePairWithDetails(ProcCalcPairwiseAAI.java:58)
	at leb.main.EzAAI.runCalculate(EzAAI.java:350)
	at leb.main.EzAAI.run(EzAAI.java:482)
	at leb.main.EzAAI.main(EzAAI.java:517)
[MAR 07 16:12:42] ERROR   |:  Program terminated with error.

-------------------------------
I just don't know if it was just my fault, because I am totally new to this "coding" world. 
I hope you could attend to this query despite of your hectic schedules. 

Thank you.

**Comment by JA00156** [comment]
Thank you so much for your swift response.

I have run the modules with the -dev option as recommended. Below is the message generated:

$ java -jar EzAAI.jar extract -i fasta/Ad.fasta -o db/Ad.b -l "Actinobacillus delphinicola" -dev
[MAR 07 17:42:46] EzAAI   |:  EzAAI - v1.2 [Mar. 2022]
[MAR 07 17:42:46] DEV     |:  EzAAI - extract module
[MAR 07 17:42:46] EzAAI   |:  Running prodigal on genome fasta/Ad.fasta...
[MAR 07 17:42:46] DEV     |:  exec: /bin/bash -c prodigal -i fasta/Ad.fasta -f gff -o /tmp/3ff259f55736d50.gff -a /home/phd/ezaai-1.2-/fasta/Ad.fasta.faa -d /tmp/3ff259f55736d50.ffn -q -p meta -g 11
[MAR 07 17:42:57] EzAAI   |:  Creating a submodule for converting .faa into .db profile...
[MAR 07 17:42:57] DEV     |:  EzAAI - convert module
[MAR 07 17:42:57] EzAAI   |:  Converting given CDS file into profile database... (fasta/Ad.fasta.faa -> db/Ad.b)
[MAR 07 17:42:57] DEV     |:  exec: mkdir /tmp/29ff4c7f27abf175
[MAR 07 17:42:57] DEV     |:  exec: /bin/bash -c mmseqs createdb /tmp/29ff4c7f27abf175.faa /tmp/29ff4c7f27abf175/mm
[MAR 07 17:42:57] DEV     |:  Writing file /tmp/29ff4c7f27abf175/mm.label
[MAR 07 17:42:57] DEV     |:  exec: /tmp/29ff4c7f27abf175$ tar -c -z -f mm.tar.gz mm mm.dbtype mm.index mm.lookup mm.source mm_h mm_h.dbtype mm_h.index mm.label
[MAR 07 17:42:57] DEV     |:  exec: mv /tmp/29ff4c7f27abf175/mm.tar.gz db/Ad.b
[MAR 07 17:42:57] EzAAI   |:  Conversion finished.
[MAR 07 17:42:57] EzAAI   |:  Task finished.


$ java -jar EzAAI.jar calculate -i db/ -j db/ -o out/aai.tsv -dev
[MAR 07 17:44:10] EzAAI   |:  EzAAI - v1.2 [Mar. 2022]
[MAR 07 17:44:10] DEV     |:  EzAAI - calculate module
[MAR 07 17:44:10] DEV     |:  exec: tar -x -z -f /home/phd/ezaai-1.2-/db/Ac.db
[MAR 07 17:44:10] DEV     |:  exec: /bin/bash -c mmseqs convert2fasta mm /tmp/67fe5377d46463da_faa/i0.faa
[MAR 07 17:44:11] DEV     |:  exec: tar -x -z -f /home/phd/ezaai-1.2-/db/Ad.b
[MAR 07 17:44:11] DEV     |:  exec: /bin/bash -c mmseqs convert2fasta mm /tmp/67fe5377d46463da_faa/i1.faa
[MAR 07 17:44:11] DEV     |:  exec: tar -x -z -f /home/phd/ezaai-1.2-/db/Ac.db
[MAR 07 17:44:11] DEV     |:  exec: /bin/bash -c mmseqs convert2fasta mm /tmp/67fe5377d46463da_faa/j0.faa
[MAR 07 17:44:11] DEV     |:  exec: tar -x -z -f /home/phd/ezaai-1.2-/db/Ad.b
[MAR 07 17:44:11] DEV     |:  exec: /bin/bash -c mmseqs convert2fasta mm /tmp/67fe5377d46463da_faa/j1.faa
[MAR 07 17:44:12] EzAAI   |:  Calculating AAI... [Task 1/4]
java.io.FileNotFoundException: /tmp/67fe5377d46463da_faa/i0.faa (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at leb.process.ProcCalcPairwiseAAI.pairwiseMmseqs(ProcCalcPairwiseAAI.java:308)
	at leb.process.ProcCalcPairwiseAAI.calculateProteomePairWithDetails(ProcCalcPairwiseAAI.java:58)
	at leb.main.EzAAI.runCalculate(EzAAI.java:350)
	at leb.main.EzAAI.run(EzAAI.java:482)
	at leb.main.EzAAI.main(EzAAI.java:517)
[MAR 07 17:44:12] ERROR   |:  Program terminated with error.

Once again, thank you.

**Comment by endix1029** [comment]
Seems like there is no particular problem from the messages themselves.

Could you please run the program using the sample dataset?
Both data and manual can be found in our [website](http://leb.snu.ac.kr/ezaai/tutorial).

If the program works fine with these samples, your sequence data might be incompatible.
Otherwise, your working environment might be inaccurately set.

Please inform me the result in your meantime.

Thanks!

**Comment by JA00156** [comment]
Thank you for your response. We have reset our working environment and the tool is now perfectly working. My apologies for troubling you. 

Our sincere appreciation for making this tool accessible to everyone.
